CREATE SEQUENCE CONFIRM_SEQ;

CREATE TABLE TBL_CONFIRM(
	REVIEW_NO NUMBER(10),
	STORE_NAME VARCHAR2(100) NOT NULL,
	STORE_ADDRESS VARCHAR2(100) NOT NULL,
	REVIEW_VIEW NUMBER(10) NOT NULL,
	REVIEW_DATE DATE NOT NULL,
	CONSTRAINT CONFIRM_PK PRIMARY KEY(REVIEW_NO)
);


SELECT * FROM TBL_CONFIRM;

INSERT INTO TBL_CONFIRM VALUES(CONFIRM_SEQ.NEXTVAL, '강식당', '식당 주소', 5, TO_DATE('20000101', 'YYYYMMDD'));
INSERT INTO TBL_CONFIRM VALUES(CONFIRM_SEQ.NEXTVAL, '존나맛있는식당', '식당 주소2', 27, TO_DATE('20110201', 'YYYYMMDD'));


SELECT * FROM (SELECT ROWNUM R, N.* FROM (SELECT * FROM TBL_CONFIRM ORDER BY REVIEW_DATE DESC) N)S


