CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TBL_NOTICE(
	NOTICE_NO NUMBER(10),
	NOTICE_TITLE VARCHAR2(100),
	NOTICE_CONTENT VARCHAR2(2000),
	NOTICE_TYPE VARCHAR2(100),
	NOTICE_DATE DATE,
	CONSTRAINT NOTICE_PK PRIMARY KEY(NOTICE_NO)
);

SELECT * FROM TBL_NOTICE;

INSERT INTO TBL_NOTICE VALUES(SEQ_NOTICE.NEXTVAL, '글쓰는 방법', '스스로 알아보자', '서비스', SYSDATE);

SELECT * FROM (SELECT ROWNUM R, N.* FROM (SELECT * FROM TBL_NOTICE ORDER BY NOTICE_DATE DESC) N)S


DELETE FROM TBL_NOTICE WHERE NOTICE_NO = 22;

SELECT * FROM (SELECT ROWNUM R, T.* FROM ((SELECT * FROM TBL_NOTICE WHERE NOTICE_TYPE = '이벤트' AND NOTICE_TITLE LIKE '%회원%') ORDER BY 1 DESC) T) S
WHERE S.R > 0 AND S.R < 5;