CREATE TABLE TBL_RANK(
   RANK_NO NUMBER(1),
   RANK_NAME VARCHAR2(100),
   RANK_REVIEW NUMBER(10),
   RANK_HEART NUMBER(10),
   RANK_FILE_NAME VARCHAR2(100),
   CONSTRAINT RANK_PK PRIMARY KEY(RANK_NO)
);

SELECT * FROM TBL_RANK;

INSERT INTO TBL_RANK
VALUES(1, '새내기', 0, 0, 'rice1.svg');

INSERT INTO TBL_RANK
VALUES(2, '브론즈', 1, 0, 'rice2.svg');

INSERT INTO TBL_RANK
VALUES(3, '실버', 2, 3, 'rice3.svg');

INSERT INTO TBL_RANK
VALUES(4, '골드', 50, 500, 'rice4.svg');

DROP TABLE TBL_RANK;