CREATE SEQUENCE REVIEW_SEQ;

CREATE TABLE TBL_REVIEW(
   REVIEW_NO NUMBER(10),
   REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
   MEM_NO NUMBER(10),
   REVIEW_HEART NUMBER(10),
   REVIEW_VIEWS NUMBER(10),
   REVIEW_DATE DATE,
   REVIEW_STAR NUMBER(10),
   RES_NAME VARCHAR2(100),
   RES_URL VARCHAR2(100),
   CONSTRAINT REVIEW_PK PRIMARY KEY(REVIEW_NO),
   CONSTRAINT REVIEW_FK FOREIGN KEY(MEM_NO) REFERENCES TBL_MEMBER(MEM_NO)
);


SELECT REVIEW_HEART FROM TBL_REVIEW WHERE REVIEW_NO = 70;
DELETE FROM TBL_REVIEW WHERE REVIEW_NO = 227;
SELECT * FROM TBL_REVIEW;
DELETE FROM TBL_REVIEW;

UPDATE TBL_REVIEW
SET REVIEW_CONTENT = '하이하이하이', 
	REVIEW_STAR = 2,
	RES_NAME = '맥도날드',
	RES_URL = 'www.naver.com',
	RES_ADDRESS = '성북도!',
	REVIEW_DONE = 0
WHERE REVIEW_NO = 4;

SELECT MEM_NO FROM TBL_REVIEW WHERE REVIEW_NO = 42; 

CREATE SEQUENCE HEART_SEQ;

CREATE TABLE TBL_HEART (
	REVIEW_NO NUMBER(10) REFERENCES TBL_REVIEW(REVIEW_NO),
	MEM_NO NUMBER(10) REFERENCES TBL_MEMBER(MEM_NO)
);

UPDATE TBL_REVIEW
SET REVIEW_HEART = (SELECT COUNT(*) FROM TBL_HEART WHERE REVIEW_NO = 81)
WHERE REVIEW_NO = 81;

SELECT COUNT(*) FROM TBL_HEART WHERE REVIEW_NO = #{review_no} AND MEM_NO = #{mem_no}

INSERT INTO TBL_HEART VALUES(72, 42);
SELECT COUNT(*) FROM TBL_HEART WHERE REVIEW_NO = 81;
SELECT * FROM TBL_HEART;

SELECT COUNT(*) FROM TBL_HEART WHERE REVIEW_NO = 72;
SELECT COUNT(*) FROM TBL_HEART WHERE REVIEW_NO = 72 AND MEM_NO = 42;

INSERT INTO TBL_HEART(HEART_NO, REVIEW_NO, MEM_NO, HEART_CHECK) 
VALUES((SELECT NVL(MAX(HEART_NO),0) + 1 AS HEART_NO FROM TBL_HEART), 
	72, 42,0
);

SELECT NVL(MAX(HEART_NO),0) + 1 AS HEART_NO FROM TBL_HEART;

DROP TABLE TBL_HEART;
DELETE FROM TBL_HEART;
DELETE FROM TBL_SCRAP;
DELETE FROM TBL_HEART WHERE REVIEW_NO = 2 AND MEM_NO =4;

CREATE TABLE TBL_FILES(
   REVIEW_NO NUMBER(10),
   FILE_NAME VARCHAR2(100),
   CONSTRAINT FILE_FK FOREIGN KEY(REVIEW_NO) REFERENCES TBL_REVIEW(REVIEW_NO),
   CONSTRAINT FILE_PK PRIMARY KEY(FILE_NAME)
);

SELECT * FROM TBL_FILES;
DELETE FROM TBL_FILES;

INSERT INTO TBL_FILES VALUES(4, 'id');CREATE SEQUENCE REVIEW_SEQ;

SELECT * FROM TBL_REVIEW;
ALTER TABLE TBL_REVIEW ADD REVIEW_DONE NUMBER(1);
ALTER TABLE TBL_REVIEW ADD REVIEW_ADDRESS VARCHAR2(100);
ALTER TABLE TBL_REVIEW RENAME COLUMN REVIEW_ADDRESS TO RES_ADDRESS;

/*당일 날짜 하트 수 순서대로 자른 리스트*/
SELECT * FROM (SELECT * FROM TBL_REVIEW WHERE (TO_CHAR(REVIEW_DATE, 'YYYYMMDD') = (SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL)) ORDER BY REVIEW_HEART DESC)WHERE ROWNUM <= 12;
SELECT SYSDATE FROM DUAL;
ALTER TABLE TBL_REVIEW MODIFY RES_URL VARCHAR2(200);
ALTER TABLE TBL_REVIEW MODIFY REVIEW_CONTENT NULL;

/*해당 날짜 쿼리문*/
INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL, '테스트', 3, 0, 0, TO_DATE('20000101', 'YYYYMMDD'), 0, NULL, NULL);

SELECT FILE_NAME FROM TBL_FILES WHERE REVIEW_NO = 53;
UPDATE TBL_REVIEW SET REVIEW_HEART = '13' WHERE REVIEW_NO = '68';