CREATE SEQUENCE SCRAP_SEQ;

CREATE TABLE TBL_SCRAP (
    SCRAP_NO NUMBER(10),
   MEM_NO NUMBER(10),
    REVIEW_NO NUMBER(10),
    CONSTRAINT SCRAP_MEMBER_FK FOREIGN KEY(MEM_NO) REFERENCES TBL_MEMBER(MEM_NO),
    CONSTRAINT SCRAP_REVIEW_FK FOREIGN KEY(REVIEW_NO) REFERENCES TBL_REVIEW(REVIEW_NO),
    CONSTRAINT SCRAP_PK PRIMARY KEY(SCRAP_NO)
);