CREATE SEQUENCE MEM_SEQ;

CREATE TABLE TBL_MEMBER(
	MEM_NO NUMBER(10),
	MEM_ID VARCHAR2(100) NOT NULL,
	MEM_PW VARCHAR2(100) NOT NULL,
	MEM_NAME VARCHAR2(100) NOT NULL,
	MEM_NICKNAME VARCHAR2(100) NOT NULL,
	MEM_TEL VARCHAR2(100) NOT NULL,
	MEM_BIRTH DATE NOT NULL,
	MEM_POINT NUMBER(10) DEFAULT 0,
	MEM_REVIEW_CNT NUMBER(10) DEFAULT 0,
	MEM_HEART NUMBER(10) DEFAULT 0,
	MEM_PHOTO BLOB,
	MEM_RANK NUMBER(1) DEFAULT 1,
	CONSTRAINT MEMBER_PK PRIMARY KEY(MEM_NO)
);

INSERT INTO TBL_MEMBER
VALUES(MEM_SEQ.NEXTVAL, 'hds1234', '1234', '한동석', '강사님', '01012345678', TO_DATE('20000101', 'YYYYMMDD'), 0, 0, 0, NULL, 1);

INSERT INTO TBL_MEMBER
VALUES(MEM_SEQ.NEXTVAL, 'hds12345', '12345', '한동석석', '강사님님', '01012345678', TO_DATE('20000101', 'YYYYMMDD'), NULL);

SELECT * FROM TBL_MEMBER;
DELETE FROM TBL_MEMBER WHERE MEM_ID = 'adf';

ALTER TABLE TBL_MEMBER ADD MEM_EMAIL VARCHAR(100);
ALTER TABLE TBL_MEMBER DROP COLUMN MEM_PHOTO;
DELETE FROM TBL_MEMBER WHERE MEM_NO = 61;
DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_PROFILE_FILES(
	MEM_NO NUMBER(10),
	PROFILE_FILE_NAME VARCHAR2(100),
	CONSTRAINT PROFILE_FILES_FK FOREIGN KEY(MEM_NO) REFERENCES TBL_MEMBER(MEM_NO),
    PRIMARY KEY(MEM_NO, PROFILE_FILE_NAME)
);

SELECT * FROM TBL_PROFILE_FILES;
DROP TABLE TBL_PROFILE_FILES;

CREATE SEQUENCE HIS_SEQ;
CREATE TABLE TBL_HISTORY(
	HISTORY_NO NUMBER(10),
	MEM_NO NUMBER(10),
	RES_NAME VARCHAR2(100),
	RES_ADDRESS VARCHAR2(100),
	RES_URL VARCHAR2(200),
	HISTORY_DATE DATE,
	CONSTRAINT HISTORY_PK PRIMARY KEY(HISTORY_NO),
	CONSTRAINT HISTORY_FK FOREIGN KEY(MEM_NO) REFERENCES TBL_MEMBER(MEM_NO)
);

DROP TABLE TBL_HISTORY;
SELECT * FROM TBL_HISTORY;
SELECT * FROM TBL_HISTORY WHERE MEM_NO = 81;
SELECT * FROM TBL_HISTORY WHERE MEM_NO = 60 ORDER BY HISTORY_DATE DESC;
SELECT (TRUNC(SYSDATE, 'MI')-TO_DATE('20201222 19:20:17','YYYY-MM-DD HH24:MI:SS')) * 1440 FROM DUAL;
DELETE FROM (SELECT * FROM (SELECT ROWNUM R, H.* FROM (SELECT * FROM TBL_HISTORY ORDER BY HISTORY_DATE DESC) H) S) 
WHERE R = 1;
DELETE FROM TBL_HISTORY WHERE HISTORY_NO = 163;

SELECT HISTORY_NO FROM (SELECT * FROM TBL_HISTORY ORDER BY HISTORY_DATE DESC) WHERE MEM_NO = 60;
SELECT * FROM TBL_HISTORY WHERE MEM_NO = 60 ORDER BY HISTORY_DATE DESC;
SELECT * FROM (SELECT ROWNUM R, H.* FROM (SELECT * FROM TBL_HISTORY ORDER BY HISTORY_DATE DESC) H) S

DELETE FROM TBL_HISTORY WHERE HISTORY_NO = 107;

INSERT INTO TBL_HISTORY VALUES(HIS_SEQ.NEXTVAL, 60, '버거킹', '인천', 'www.buggerking.com');

SELECT MEM_NO FROM TBL_MEMBER WHERE MEM_ID = 'admin';
DELETE FROM TBL_HISTORY WHERE MEM_NO = 60;


CREATE TABLE TBL_AUTHORITY(
	MEM_NO NUMBER(10),
	AUTHORITY_DATE DATE,
	CONSTRAINT AUTHORITY_FK FOREIGN KEY(MEM_NO) REFERENCES TBL_MEMBER(MEM_NO),
	CONSTRAINT AUTHORITY_PK PRIMARY KEY(MEM_NO)
);

SELECT * FROM TBL_AUTHORITY;
SELECT (TRUNC(SYSDATE, 'MI')-TO_DATE('20210102 15:36:17','YYYY-MM-DD HH24:MI:SS')) * 1440 FROM DUAL;

DELETE FROM TBL_AUTHORITY WHERE MEM_NO = 81;
INSERT INTO TBL_AUTHORITY VALUES(60, SYSDATE);
DROP TABLE TBL_AUTHORITY;